name: github-actions-test

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
      # - uses: actions/checkout@v4
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - run: npm ci
      # - run: npm test
      # - run: npm run build

  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v4
  #       with:
  #         files: ./coverage/lcov.info
  #         flags: unittests
  #         name: codecov-umbrella

  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps chromium

  #     - name: Run E2E tests
  #       run: npm run test:e2e
  #       env:
  #         CI: true

  #     - name: Upload E2E test results
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30

  #     - name: Upload coverage reports
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: coverage-report
  #         path: coverage/
  #         retention-days: 30

